# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    container_name: spring-blog
    build:
      context: backend # Use an image built from the specified dockerfile in the `backend` directory.
      dockerfile: Dockerfile
    ports:
<<<<<<< HEAD
      - "8081:8081" # Forward the exposed port 8080 on the container to port 8080 on the host machine
=======
      - "8081:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
>>>>>>> 90fe94485dddd7f8e378cc67845fccf57b82bbd2
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend-blog
      - fontend-blog
    depends_on: 
      - dbblog # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://dbblog:3306/blog_dependency
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: a1234

  # # Frontend Service 
  app-client:
    build:
      context: fontend/web/Blog-Dependency # Use an image built from the specified dockerfile in the `polling-app-client` directory.
      dockerfile: Dockerfile
    ports:
      - "4200:80" # Map the exposed port 80 on the container to port 4200 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - fontend-blog 

  # Database Service (Mysql)
  dbblog:
    image: mysql
    container_name: dbblog
    # restart: always
    ports: 
      - "3308:3306"
    networks:
      - backend-blog
    environment:
      MYSQL_DATABASE: blog_dependency
      MYSQL_PASSWORD: a1234
      MYSQL_ROOT_PASSWORD: a1234
    volumes:
      - db-data:/var/lib/mysql
  
# Volumes
volumes:
  db-data:
    name: db-data

# Networks to be created to facilitate communication between containers
networks:
  backend-blog:
    name:  backend-blog
  fontend-blog:
    name: fontend-blog